### PR TITLE
Support Zulu MUSL Platform

### PR DESCRIPTION
**Pull request by maximann**
https://github.com/KoskiLabs/jdk-wrapper/issues/27

### CODE REVIEW

**Comment by maximann** [comment]
Sorry for the late follow up.

I checked and `ldd` doesn't appear to be reliably present on systems (darwin for example). If you prefer I can try ldd and fallback to the apk check.

**Comment by vjkoskela** [comment]
How about something like this:

```
libc=""
if command -v ldd > /dev/null; then
  if [ "$(ldd --version 2>&1 | grep musl | wc -l)" -gt 0 ]; then
    libc="_musl"
  fi
fi
```

I don't know enough about apk to say whether it's 1:1 with libc being musl based or not. However, querying `ldd` seems rather authoritative. If you've done more research into this please let me know if this is not an accurate/complete assessment.

**Comment by maximann** [comment]
I absolutely agree that this is authoritative, what I'm worried about is ldd not being present on all systems / containers. But I suppose it is ok to just fall back on libc for those systems.

**Comment by vjkoskela** [comment]
I am reasonably confident that `ldd` will be available on all Linux based Docker containers and environments. If it is not, I would say it's highly unlikely that the Zulu JDK would be able to install/run. 

As for other platforms, there are LDD equivalent tools on those platforms (e.g. on Mac it's `otool`). However, as far as I know there are no libc-alternative builds on other platforms from Zulu or Oracle for JDK. The flag you are adding is only being used to determine the variant to install under Linux.

The only issue I have is that the libc to be used should be overridable (e.g. you have an Alpine system where `ldd` returns `musl` but it also has libc installed on it). You could run either or both JDKs on the system afaik. You need to be careful adding this type of override since it's being consumed where the platform defaults are being set.

**Comment by vjkoskela** [comment]
This is being addressed in #29 and will be released with `0.12.0`. Closing.

**Pull request closed without merging**
